#\DeclareLyXModule[thmtools.sty]{Restate}

Format 66

AddToPreamble
	\usepackage{thmtools}
	\newcommand{\restate}[1]{\csname #1\endcsname*}
EndPreamble

Style RestatableTheorem

	CopyStyle             Theorem
	DependsOn             Theorem
	LatexName		restatableThm

	Preamble
		\newenvironment{restatableThm}[2][]
 		{\restatable[#1]{thm}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End
Style RestatableLemma

	CopyStyle             Lemma
	DependsOn             Lemma
	LatexName		restatableLem

	Preamble
		\newenvironment{restatableLem}[2][]
 		{\restatable[#1]{lem}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End
Style RestatableProposition

	CopyStyle             Proposition
	DependsOn             Proposition
	LatexName		restatableProp

	Preamble
		\newenvironment{restatableProp}[2][]
 		{\restatable[#1]{prop}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End
Style RestatableConjecture

	CopyStyle             Conjecture
	DependsOn             Conjecture
	LatexName		restatableconjecture

	Preamble
		\newenvironment{restatableconjecture}[2][]
 		{\restatable[#1]{conjecture}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End
Style RestatableFact

	CopyStyle             Fact
	DependsOn             Fact
	LatexName		restatableFact

	Preamble
		\newenvironment{restatableFact}[2][]
 		{\restatable[#1]{fact}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End
Style RestatableDefinition

	CopyStyle             Definition
	DependsOn             Definition
	LatexName		restatabledefn

	Preamble
		\newenvironment{restatabledefn}[2][]
 		{\restatable[#1]{defn}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End
Style RestatableRemark

	CopyStyle             Remark
	DependsOn             Remark
	LatexName		restatableRem

	Preamble
		\newenvironment{restatableRem}[2][]
 		{\restatable[#1]{rem}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End
Style RestatableClaim

	CopyStyle             Claim
	DependsOn             Claim
	LatexName		restatableClaim

	Preamble
		\newenvironment{restatableClaim}[2][]
 		{\restatable[#1]{claim}{#2}}
 		{\endrestatable}
	EndPreamble

	Argument 2
		LabelString    "Restate Label"
		Tooltip        "The label use for restating"
		IsTocCaption      0
		Mandatory 1
	EndArgument
End

Style Restate
	Category              Reasoning
	LatexType             Command
	Margin                First_Dynamic
	LatexName             restate
	LabelType             Static
	LabelString           "Restate."
	NextNoIndent          1
	ResetArgs             1
	IsTocCaption          1
	LabelSep              xx
	ParIndent             MMM
	ParSkip               0.4
	ItemSep               0.2
	TopSep                0.7
	BottomSep             0.7
	ParSep                0.3
	Align                 Block
	AlignPossible         Left
	Font
	  Shape               Italic
	  Size                Normal
	EndFont
	LabelFont
	  Shape               Up
	  Series              Bold
	EndFont
End