#! /bin/bash

tmp_file="/tmp/ohbarak.tmp.mp3"
mktemp $tmp_file


test_file="/tmp/ohbarak_running_flag"
# mktemp $test_file

[ ! -f "$test_file" ] && {
    # echo called >> "/Users/obama/.config/Übersicht/widgets/ohbarak.widget/call_tracker"
    mktemp $test_file

    /opt/homebrew/bin/wget -q -O $tmp_file $1 



    /opt/homebrew/bin/mplayer -quiet $tmp_file

    rm "$tmp_file"
    rm "$test_file"
}


